import { readFile } from 'node:fs/promises'
import { expect, test, type Page } from '@playwright/test'
const key = 'creatordock.distributions.v1'
async function create(page: Page, title = '把一份内容分发到多个平台') {
  await page.getByRole('button', { name: '＋ 新建分发', exact: true }).first().click()
  const editor = page.getByRole('dialog', { name: '新建分发', exact: true })
  await editor.getByLabel('内容标题', { exact: true }).fill(title)
  await editor.getByLabel('正文', { exact: true }).fill('这是手动准备的真实测试文案。保留原文，为不同平台调整表达。')
  await editor.getByRole('checkbox', { name: '小红书', exact: true }).check()
  await editor.getByRole('checkbox', { name: '微信公众号', exact: true }).check()
  await editor.getByRole('button', { name: '创建分发', exact: true }).click()
  await expect(editor).not.toBeVisible()
}
test('creates, copies, independently publishes, reloads, exports and reversibly archives', async ({ page, context }) => {
  await context.grantPermissions(['clipboard-read', 'clipboard-write'])
  await page.goto('')
  await expect(page.getByRole('heading', { name: '从第一份内容开始' })).toBeVisible()
  await create(page)
  await expect(page.getByText('0/2 个平台已完成')).toBeVisible()
  await page.getByRole('button', { name: '复制正文', exact: true }).click()
  expect(await page.evaluate(() => navigator.clipboard.readText())).toContain('真实测试文案')
  await page.getByLabel('发布链接', { exact: true }).fill('javascript:alert(1)')
  await page.getByRole('button', { name: '✓ 标记已发布' }).click()
  await expect(page.getByRole('alert')).toContainText('有效的 http 或 https 链接')
  await page.getByLabel('发布链接', { exact: true }).fill('https://example.com/published')
  await page.getByRole('button', { name: '✓ 标记已发布' }).click()
  await expect(page.getByRole('tab', { name: '进行中 1' })).toHaveAttribute('aria-selected','true')
  await expect(page.getByText('1/2 个平台已完成')).toBeVisible()
  await page.locator('.dock-target-list').getByRole('button', { name: /微信公众号/ }).click()
  await page.getByRole('button', { name: '✓ 标记已发布' }).click()
  await expect(page.getByRole('tab', { name: '已完成 1' })).toHaveAttribute('aria-selected','true')
  await expect(page.getByText('2/2 个平台已完成')).toBeVisible()
  await page.reload()
  await page.getByRole('tab', { name: '已完成 1' }).click()
  await expect(page.getByText('2/2 个平台已完成')).toBeVisible()
  const [download] = await Promise.all([page.waitForEvent('download'), page.getByRole('button', { name: '导出文案', exact: true }).click()])
  const text = await readFile((await download.path())!, 'utf8')
  expect(text).toContain('https://example.com/published')
  expect(text.match(/状态：已发布/g)).toHaveLength(2)
  await page.getByRole('button', { name: '归档内容', exact: true }).click()
  await expect(page.getByRole('button', { name: /查看分发：/ })).toHaveCount(0)
  await page.getByRole('button', { name: '内容库', exact: true }).click()
  await page.getByRole('button', { name: '已归档', exact: true }).click()
  await expect(page.getByRole('button', { name: /查看分发：/ })).toHaveCount(1)
  await page.getByRole('button', { name: '恢复内容', exact: true }).click()
  await page.getByRole('button', { name: '全部内容', exact: true }).click()
  await expect(page.getByRole('button', { name: /查看分发：/ })).toHaveCount(1)
  const saved = await page.evaluate(key => JSON.parse(localStorage.getItem(key)!), key)
  expect(saved.records[0].targets.every((t: { publishedAt?: string }) => Boolean(t.publishedAt))).toBe(true)
})
test('edits platform variants without changing other platforms and restores after reload', async ({ page }) => {
  await page.goto('')
  await create(page, '平台适配验收')
  await page.getByRole('button', { name: '编辑内容', exact: true }).click()
  const editor = page.getByRole('dialog', { name: '编辑分发内容' })
  await editor.getByText('为不同平台单独调整文案', { exact: true }).click()
  await editor.getByLabel('选择平台', { exact: true }).selectOption({ label: '小红书' })
  await editor.getByLabel('平台标题', { exact: true }).fill('只用于小红书的新标题')
  await editor.getByLabel('平台正文', { exact: true }).fill('独立的平台正文')
  await editor.getByRole('button', { name: '保存修改' }).click()
  await page.reload()
  const saved = await page.evaluate(key => JSON.parse(localStorage.getItem(key)!), key)
  expect(saved.records[0].targets[0].title).toBe('只用于小红书的新标题')
  expect(saved.records[0].targets[0].body).toBe('独立的平台正文')
  expect(saved.records[0].targets[1].title).toBe('平台适配验收')
  expect(saved.records[0].targets[1].body).toContain('真实测试文案')
})
test('preserves damaged storage and rejects invalid backup without mutation', async ({ page }) => {
  await page.addInitScript(key => localStorage.setItem(key, 'broken original'), key)
  await page.goto('')
  await expect(page.getByRole('alert')).toContainText('不会被覆盖')
  await expect(page.getByRole('button', { name: '＋ 新建分发', exact: true }).first()).toBeDisabled()
  expect(await page.evaluate(key => localStorage.getItem(key), key)).toBe('broken original')
  await page.getByRole('button', { name: '设置', exact: true }).click()
  await page.getByLabel('导入分发备份', { exact: true }).setInputFiles({ name: 'bad.json', mimeType: 'application/json', buffer: Buffer.from('{}') })
  await expect(page.getByRole('status')).toContainText('分发备份格式不正确')
  expect(await page.evaluate(key => localStorage.getItem(key), key)).toBe('broken original')
})
test('mobile content flow stays within the viewport and detail has a return path', async ({ page }) => {
  await page.setViewportSize({ width:390, height:844 })
  await page.goto('')
  await create(page, '移动端分发验收')
  await page.getByRole('button', { name: '查看分发：移动端分发验收' }).click()
  await expect(page.getByRole('button', { name: '← 返回内容队列' })).toBeVisible()
  await expect(page.getByRole('button', { name: '复制正文', exact: true })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.getByRole('button', { name: '← 返回内容队列' }).click()
  await expect(page.getByRole('button', { name: '查看分发：移动端分发验收' })).toBeVisible()
  await page.screenshot({ path:'test-results/distribution-mobile.png', fullPage:true })
})
test('desktop visual checkpoint uses isolated test records, not user data', async ({ page }) => {
  await page.setViewportSize({ width:1586,height:990 })
  await page.goto('')
  await create(page,'普通人如何用 AI，把一份内容发好')
  await create(page,'把周末的灵感整理成一篇好内容')
  await create(page,'10 月内容计划：保持自己的发布节奏')
  await page.getByRole('button', { name:'查看分发：普通人如何用 AI，把一份内容发好' }).click()
  await page.getByRole('button', { name:'关闭',exact:true }).click()
  await page.screenshot({ path:'test-results/distribution-desktop.png',fullPage:true,animations:'disabled' })
  await page.getByRole('button', { name:'✓ 标记已发布' }).click()
  await page.getByRole('button', { name:'内容库',exact:true }).click()
  await page.getByRole('button', { name:'查看分发：普通人如何用 AI，把一份内容发好' }).click()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path:'test-results/distribution-library.png',fullPage:true,animations:'disabled' })
})

test('keeps new content exportable when browser storage is full', async ({ page }) => {
  await page.addInitScript(() => {
    const original = Storage.prototype.setItem
    Storage.prototype.setItem = function(key, value) {
      if (key === 'creatordock.distributions.v1') throw new DOMException('Quota exceeded', 'QuotaExceededError')
      return original.call(this, key, value)
    }
  })
  await page.goto('')
  await create(page, '存储失败也不丢失')
  await expect(page.getByRole('alert')).toContainText('保存失败')
  await expect(page.getByRole('button', { name:'查看分发：存储失败也不丢失' })).toBeVisible()
  const [download] = await Promise.all([page.waitForEvent('download'), page.getByRole('button', { name:'导出当前备份' }).click()])
  const backup = JSON.parse(await readFile((await download.path())!, 'utf8'))
  expect(backup.records[0].title).toBe('存储失败也不丢失')
  expect(backup.records[0].targets).toHaveLength(2)
})

test('carries selected content into AI without overwriting its draft and imports completed package variants', async ({ page }) => {
  await page.addInitScript(() => {
    localStorage.setItem('creatordock.writing.draft.v1', '已有写作草稿')
  })
  await page.goto('')
  await create(page, 'AI 适配来源')
  await page.getByRole('button', { name: 'AI 辅助适配 ↗', exact:true }).click()
  await expect(page.getByLabel('待适配内容')).toContainText('AI 适配来源')
  await expect(page.getByLabel('写作任务', { exact:true })).toHaveValue('已有写作草稿')
  await page.getByRole('button', { name:'带入写作任务',exact:true }).click()
  await expect(page.getByLabel('写作任务', { exact:true })).toHaveValue(/已有写作草稿[\s\S]*AI 适配来源/)
  const entries = await page.evaluate(() => JSON.parse(localStorage.getItem('creatordock.config') ?? 'null'))
  // Default entries are not saved until changed; use a seeded configuration for package migration.
  expect(entries === null || Array.isArray(entries.entries)).toBe(true)
  await page.evaluate(() => {
    const distribution = JSON.parse(localStorage.getItem('creatordock.distributions.v1')!).records[0]
    const targets = distribution.targets.map((t: {entry:{id:string;displayName:string;platformPresetId?:string}}) => ({id:t.entry.id,label:t.entry.displayName,platformPresetId:t.entry.platformPresetId}))
    const config = { schemaVersion:2, language:'zh-CN', theme:'light', density:'comfortable', entries:distribution.targets.map((t:{entry:unknown})=>t.entry) }
    localStorage.setItem('creatordock.config', JSON.stringify(config))
    localStorage.setItem('creatordock.content-packages.v1', JSON.stringify([{schemaVersion:1,id:'import-package',brief:'历史 AI 内容包',targets,variants:targets.map((target:{id:string},i:number)=>({id:`variant-${i}`,target,output:`第 ${i+1} 份独立稿件`,status:'complete'})),createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()}]))
  })
  await page.reload()
  await page.getByRole('button', { name:'加入分发队列',exact:true }).click()
  await expect(page.getByRole('heading', { name:'分发工作台',exact:true })).toBeVisible()
  const records = await page.evaluate(key=>JSON.parse(localStorage.getItem(key)!).records,key)
  expect(records).toHaveLength(2)
  expect(records[0].targets.map((t:{body:string})=>t.body)).toEqual(['第 1 份独立稿件','第 2 份独立稿件'])
  expect(await page.evaluate(()=>localStorage.getItem('creatordock.content-packages.v1'))).toContain('import-package')
})

test('validates cover uploads and downloads the saved cover intact', async ({ page }) => {
  await page.goto('')
  await create(page, '封面与备份验收')
  await page.getByRole('button', { name:'编辑内容',exact:true }).click()
  const editor = page.getByRole('dialog', { name:'编辑分发内容' })
  const input = editor.locator('input[type=file]')
  await input.setInputFiles({name:'bad.svg',mimeType:'image/svg+xml',buffer:Buffer.from('<svg/>')})
  await expect(editor.getByRole('alert')).toContainText('不超过 2 MB')
  const png = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jEakAAAAASUVORK5CYII=','base64')
  await input.setInputFiles({name:'cover.png',mimeType:'image/png',buffer:png})
  await expect(editor.getByRole('img', {name:'封面预览'})).toBeVisible()
  await editor.getByRole('button', {name:'保存修改'}).click()
  await page.reload()
  const [download] = await Promise.all([page.waitForEvent('download'),page.getByRole('link',{name:'下载封面'}).click()])
  expect(await readFile((await download.path())!)).toEqual(png)
})

test('imports backups by merging and retaining a conflicting record as a copy', async ({page}) => {
  await page.goto('')
  await create(page,'保留原始文案')
  const backup = await page.evaluate(key=>JSON.parse(localStorage.getItem(key)!),key)
  backup.records[0].title = '冲突的导入文案'
  await page.getByRole('button',{name:'设置',exact:true}).click()
  await page.getByLabel('导入分发备份',{exact:true}).setInputFiles({name:'backup.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(backup))})
  await expect(page.getByRole('status')).toContainText('已导入 1 条内容')
  await page.reload()
  await page.getByRole('button',{name:'内容库',exact:true}).click()
  await expect(page.getByRole('button',{name:'查看分发：保留原始文案'})).toBeVisible()
  await expect(page.getByRole('button',{name:'查看分发：冲突的导入文案（导入副本）'})).toBeVisible()
})

test('preserves additions from another tab when saving an older open workspace', async ({page, context}) => {
  await page.goto('')
  await create(page, '原有分发内容')
  const other = await context.newPage()
  await other.goto('')
  await create(other, '另一标签页新增内容')
  await page.getByRole('button',{name:'✓ 标记已发布'}).click()
  await page.reload()
  await page.getByRole('button',{name:'内容库',exact:true}).click()
  await expect(page.getByRole('button',{name:'查看分发：原有分发内容'})).toBeVisible()
  await expect(page.getByRole('button',{name:'查看分发：另一标签页新增内容'})).toBeVisible()
})

test('keeps both versions when two tabs edit the same content', async ({page, context}) => {
  await page.goto('')
  await create(page, '共同编辑的内容')
  const other = await context.newPage()
  await other.goto('')
  await page.getByRole('button',{name:'编辑内容',exact:true}).click()
  await other.getByRole('button',{name:'编辑内容',exact:true}).click()
  const otherEditor = other.getByRole('dialog',{name:'编辑分发内容'})
  await otherEditor.getByLabel('正文',{exact:true}).fill('另一标签页独有的修改')
  await otherEditor.getByRole('button',{name:'保存修改'}).click()
  const editor = page.getByRole('dialog',{name:'编辑分发内容'})
  await editor.getByLabel('正文',{exact:true}).fill('当前标签页独有的修改')
  await editor.getByRole('button',{name:'保存修改'}).click()
  await expect(page.getByText(/检测到其他标签页修改了相同内容/)).toBeVisible()
  await page.reload()
  const records = await page.evaluate(key=>JSON.parse(localStorage.getItem(key)!).records,key)
  expect(records).toHaveLength(2)
  expect(records.map((r:{body:string})=>r.body)).toEqual(expect.arrayContaining(['另一标签页独有的修改','当前标签页独有的修改']))
})

test('retains unchanged in-memory records when importing a repaired backup after external corruption', async ({page}) => {
  await page.goto('')
  await create(page, '应该保留的内容')
  await create(page, '正在操作的内容')
  await page.evaluate(key=>localStorage.setItem(key,'broken externally'),key)
  await page.getByRole('button',{name:'✓ 标记已发布'}).click()
  await expect(page.getByRole('alert')).toContainText('已停止覆盖')
  await page.getByRole('button',{name:'设置',exact:true}).click()
  await page.getByLabel('导入分发备份',{exact:true}).setInputFiles({name:'repaired.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({schemaVersion:1,records:[]}))})
  await expect(page.getByText('已导入 0 条内容；已有内容保留。')).toBeVisible()
  await page.reload()
  await page.getByRole('button',{name:'内容库',exact:true}).click()
  await expect(page.getByRole('button',{name:'查看分发：应该保留的内容'})).toBeVisible()
  await expect(page.getByRole('button',{name:'查看分发：正在操作的内容'})).toBeVisible()
})
